name: Daily Data Pull

on:
  schedule:
    - cron: '0 8 * * *'  # Schedule to run every day at 8 AM UTC

jobs:
  data_pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install Dependencies
        run: pip install -r requirements.txt  

      - name: Run Data Pull Script
        run: python DublinBikeDataPull.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "githubaction@github.com"

      - name: Commit and Push CSV
        run: |
          git add dublinbikes.csv
          git commit -m "Update dublinbikes.csv with new data"
          git push
